const pool = require("../config/database");

async function createUsersTable() {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(50) UNIQUE NOT NULL,
        email varchar(100) UNIQUE NOT NULL,
        password_hash varchar(255) NOT NULL,
        role_id integer REFERENCES roles(id),
        created_at timestamp DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log("Users table created successfully");
  } catch (error) {
    console.error("Error creating users table:", error);
  } finally {
    client.release();
  }
}

module.exports = createUsersTable;
