const pool = require("../config/database");

async function createSalesTable() {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS sales (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        cashier VARCHAR(255),
        sale_date DATE NOT NULL,
        customer_name VARCHAR(255),
        total_amount DECIMAL(12, 2) NOT NULL,
        status VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log("Sales table created successfully");
  } catch (error) {
    console.error("Error creating sales table:", error);
  } finally {
    client.release();
  }
}

module.exports = createSalesTable;
