const pool = require("../config/database");

async function createPurchasesTable() {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_id INTEGER REFERENCES suppliers(id) ON DELETE SET NULL,
        supplier_name VARCHAR(255),
        purchase_date DATE NOT NULL,
        total_amount DECIMAL(12, 2) NOT NULL,
        status VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log("Purchases table created successfully");
  } catch (error) {
    console.error("Error creating purchases table:", error);
  } finally {
    client.release();
  }
}

module.exports = createPurchasesTable;
