const pool = require("../config/database");

async function createPurchaseItemsTable() {
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        purchase_id INTEGER REFERENCES purchases(id),
        medicine_id INTEGER REFERENCES medicines(id) ON DELETE SET NULL,
        medicine_name VARCHAR(255),
        quantity INTEGER NOT NULL,
        unit_price DECIMAL(10, 2) NOT NULL,
        total_price DECIMAL(12, 2) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log("Purchase Items table created successfully");
  } catch (error) {
    console.error("Error creating purchase_items table:", error);
  } finally {
    client.release();
  }
}

module.exports = createPurchaseItemsTable;
